//****************************************************************************************

//   Copyright 2023 Scaledge India Pvt Ltd - All Rights Reserved.

//   Owner: Auroshree Anuvab Raj

//   Item : rv32i- load store instruction

//   Date created : 11/07/2025

//***********************************************************************************
//   Description: load and store of data into registers and memory
//***********************************************************************************


#include "test_macros.h"
 
#include "riscv_test.h"
RVTEST_RV32M
 
RVTEST_CODE_BEGIN


 .data:
mydata: .byte 0xFF    //defines a byte in the memory


start:
//address range 0x70000000 - 0x80000000 

Test1: 		//Load Byte with incrementing Address
li		x5,	0x70000000
load_loop:
lb		x6,	0(x5)
addi	x5,	x5,	1
li		x7,	0x80000000
blt	x5,	x7,		load_loop




 
  TEST_PASSFAIL
RVTEST_CODE_END
  .data
RVTEST_DATA_BEGIN
 
  TEST_DATA

inp_data:
 
  .word 0x06627912
 
  .word 0x06627912
 
  .word 0x584944fc
 
  .word 0x584944fc
 
  .word 0x558f5366
 
  .word 0x558f5366
 
  .word 0x29df2fb1
 
  .word 0x29df2fb1
 
  .word 0x40053e92
 
  .word 0x40053e92
 
  .word 0x17010699
 
  .word 0x17010699
 
  .word 0x594b9169
 
  .word 0x594b9169
 
  .word 0x64cd11c7
 
  .word 0x64cd11c7
 
  .word 0x6133a31e
 
  .word 0x6133a31e
 
  .word 0x2a9e3a3d
 
  .word 0x2a9e3a3d
 
  .word 0x59f86117
 
  .word 0x59f86117
 
  .word 0x39214611
 
  .word 0x39214611
 
  .word 0x6ec633f5
 
  .word 0x6ec633f5
 
  .word 0x4910a7b3
 
  .word 0x4910a7b3
 
  .word 0x3392ec72
 
  .word 0x3392ec72
 
  .word 0x6c3af175
 
  .word 0x6c3af175
 
  .word 0x74555adb
 
  .word 0x74555adb
 
  .word 0x360a50f7
 
  .word 0x360a50f7
 
  .word 0x39febbec
 
  .word 0x39febbec
 
  .word 0x28cb8c74
 
  .word 0x28cb8c74
RVTEST_DATA_END

