//****************************************************************************************
 
//   Copyright 2023 Scaledge India Pvt Ltd - All Rights Reserved.
 
//   Owner: Auroshree Anuvab Raj
 
//   Item : rv32m- mul and div instruction
 
//   Date created : 11/10/2025
 
//***********************************************************************************
//   Description: all multipication and division instruction
//***********************************************************************************
 
 
#include "test_macros.h"
#include "riscv_test.h"
RVTEST_RV64M
RVTEST_CODE_BEGIN
  li gp, 3
 
 
start:
//the testintention isto sub,addimmediate with a negative number

Test1:	//mulw
	li		x5,	0x7FFFFFFF
	li		x6,	5
	mulw	x7,	x5,	x6	//x7=0x7FFFFFFF*5=0x2FFFFFFFB

Test2:	//divw
	li		x5,	-100
	li		x6,	0
	divw	x7,	x5,	x6

Test3:	//divuw
	li		x5,	-100
	li		x6,	2
	divuw	x7,	x5,	x6

Test4:	//remw
	li		x5,	-234
	li		x6,	5
	remw	x7,	x5,	x6

Test5:	//remuw
	li		x5,	-234
	li		x6,	5
	remuw	x7,	x5,	x6


TEST_PASSFAIL
RVTEST_CODE_END
.data
RVTEST_DATA_BEGIN

TEST_DATA

inp_data:
.word 0x06627912
.word 0x06627912
.word 0x584944fc
.word 0x584944fc
.word 0x558f5366
.word 0x558f5366
.word 0x29df2fb1
.word 0x29df2fb1
.word 0x40053e92
.word 0x40053e92
.word 0x17010699
.word 0x17010699
.word 0x594b9169
.word 0x594b9169
.word 0x64cd11c7
.word 0x64cd11c7
.word 0x6133a31e
.word 0x6133a31e
.word 0x2a9e3a3d
.word 0x2a9e3a3d
.word 0x59f86117
.word 0x59f86117
.word 0x39214611
.word 0x39214611
.word 0x6ec633f5
.word 0x6ec633f5
.word 0x4910a7b3
.word 0x4910a7b3
.word 0x3392ec72
.word 0x3392ec72
.word 0x6c3af175
.word 0x6c3af175
.word 0x74555adb
.word 0x74555adb
.word 0x360a50f7
.word 0x360a50f7
.word 0x39febbec
.word 0x39febbec
.word 0x28cb8c74
.word 0x28cb8c74
RVTEST_DATA_END
